/*-------------------------------------------------------------------------
 *
 * mk_qsort_tuple_template.h
 *	  Template for tuple- and comparator-specific mksort operations.
 *
 * Copyright (c) 2026, PostgreSQL Global Development Group
 *
 * Before including this file, define:
 *
 * MKQS_BASE_NAME
 *	  Suffix used to name all functions generated by this instantiation.
 *
 * MKQS_GET_DATUM
 *	  Inline function that extracts the current sort key's datum from a
 *	  SortTuple.
 *
 * MKQS_COMPARE_DATUM
 *	  Inline function that compares two non-NULL datums in the sort
 *	  operator's natural direction.
 *
 * MKQS_USE_ABBREVIATION
 *	  1 when the generated functions must handle abbreviated leading datums,
 *	  or 0 when abbreviation is excluded by dispatch.
 *
 * IDENTIFICATION
 *	  src/backend/utils/sort/mk_qsort_tuple_template.h
 *
 *-------------------------------------------------------------------------
 */

#if !defined(MKQS_BASE_NAME) || !defined(MKQS_GET_DATUM) || \
	!defined(MKQS_COMPARE_DATUM) || !defined(MKQS_USE_ABBREVIATION)
#error "MKQS template parameters must be defined"
#endif

/* Derive all generated function names from the caller-supplied base name. */
#define MKQS_MAKE_PREFIX(a) CppConcat(a,_)
#define MKQS_MAKE_NAME(a,b) MKQS_MAKE_NAME_(MKQS_MAKE_PREFIX(a),b)
#define MKQS_MAKE_NAME_(a,b) CppConcat(a,b)
#define MKQS_COMPARE_TUPLE \
	MKQS_MAKE_NAME(mkqs_compare_tuple, MKQS_BASE_NAME)
#define MKQS_PARTITION MKQS_MAKE_NAME(mkqs_partition, MKQS_BASE_NAME)
#define MKQS_COMPARE_TO_PIVOT \
	MKQS_MAKE_NAME(mkqs_compare_to_pivot, MKQS_BASE_NAME)
#define MKQS_APPLY_COMPARE \
	MKQS_MAKE_NAME(mkqs_apply_compare, MKQS_BASE_NAME)

/* Apply common NULL and sort-direction semantics around a typed comparison. */
static pg_attribute_always_inline int
MKQS_APPLY_COMPARE(Datum datum1, bool isNull1,
				   Datum datum2, bool isNull2,
				   SortSupport sortKey)
{
	int			compare;

	if (isNull1 || isNull2)
	{
		if (isNull1 && isNull2)
			return 0;
		return isNull1 == sortKey->ssup_nulls_first ? -1 : 1;
	}

	compare = MKQS_COMPARE_DATUM(datum1, datum2, sortKey);
	if (sortKey->ssup_reverse)
		INVERT_COMPARE_RESULT(compare);
	return compare;
}

/* Compare two SortTuples at exactly one sort-key depth. */
static int
MKQS_COMPARE_TUPLE(SortTuple *a, SortTuple *b, int depth,
				   Tuplesortstate *state)
{
	SortSupport sortKey = &state->base.sortKeys[depth];
	Datum		datum1;
	Datum		datum2;
	bool		isNull1;
	bool		isNull2;
	int			compare;

	if (depth == 0)
	{
		/* datum1 caches the leading key, possibly in abbreviated form. */
		compare = MKQS_APPLY_COMPARE(a->datum1, a->isnull1,
									 b->datum1, b->isnull1, sortKey);
#if MKQS_USE_ABBREVIATION
		if (compare != 0 || !sortKey->abbrev_converter ||
			a->isnull1 || b->isnull1)
			return compare;

		/* Equal abbreviations must be resolved using the full datums. */
		datum1 = MKQS_GET_DATUM(a, sortKey, state, &isNull1);
		datum2 = MKQS_GET_DATUM(b, sortKey, state, &isNull2);
		Assert(!isNull1 && !isNull2);
		return mkqs_compare_abbrev_full_datum(datum1, datum2, sortKey);
#else
		return compare;
#endif
	}

	datum1 = MKQS_GET_DATUM(a, sortKey, state, &isNull1);
	datum2 = MKQS_GET_DATUM(b, sortKey, state, &isNull2);
	return MKQS_APPLY_COMPARE(datum1, isNull1, datum2, isNull2, sortKey);
}

/* Compare one tuple with the cached pivot using the specialized accessor. */
static pg_attribute_always_inline int
MKQS_COMPARE_TO_PIVOT(SortTuple *tuple, int depth,
					  Tuplesortstate *state, SortSupport sortKey,
					  Datum pivotDatum, bool pivotIsNull,
					  Datum pivotFullDatum)
{
	Datum		datum;
	bool		isNull;
	int			compare;

	if (depth == 0)
	{
		compare = MKQS_APPLY_COMPARE(tuple->datum1, tuple->isnull1,
									 pivotDatum, pivotIsNull, sortKey);
#if MKQS_USE_ABBREVIATION
		if (compare != 0 || !sortKey->abbrev_converter ||
			tuple->isnull1 || pivotIsNull)
			return compare;

		datum = MKQS_GET_DATUM(tuple, sortKey, state, &isNull);
		Assert(!isNull);
		return mkqs_compare_abbrev_full_datum(datum, pivotFullDatum, sortKey);
#else
		return compare;
#endif
	}

	datum = MKQS_GET_DATUM(tuple, sortKey, state, &isNull);
	return MKQS_APPLY_COMPARE(datum, isNull, pivotDatum, pivotIsNull, sortKey);
}

/* Partition tuples around x[0], comparing only the current key depth. */
static bool
MKQS_PARTITION(SortTuple *x, size_t n, int depth,
			   Tuplesortstate *state,
			   MkqsPartitionBounds *bounds)
{
	SortSupport sortKey = &state->base.sortKeys[depth];
	Datum		pivotDatum;
	Datum		pivotFullDatum = (Datum) 0;
	bool		pivotIsNull;
	int32		dist;

	/* Extract the pivot once before scanning the rest of the partition. */
	if (depth == 0)
	{
		pivotDatum = x->datum1;
		pivotIsNull = x->isnull1;
#if MKQS_USE_ABBREVIATION
		if (sortKey->abbrev_converter && !pivotIsNull)
		{
			bool		isNull;

			pivotFullDatum = MKQS_GET_DATUM(x, sortKey, state, &isNull);
			Assert(!isNull);
		}
#endif
	}
	else
		pivotDatum = MKQS_GET_DATUM(x, sortKey, state, &pivotIsNull);

	bounds->lessStart = 1;
	bounds->lessEnd = 1;
	bounds->greaterStart = n - 1;
	bounds->greaterEnd = n - 1;

	while (true)
	{
		CHECK_FOR_INTERRUPTS();

		/* Scan from the left, moving equal values to the left edge. */
		while (bounds->lessEnd <= bounds->greaterStart)
		{
			dist = MKQS_COMPARE_TO_PIVOT(x + bounds->lessEnd, depth,
										 state, sortKey,
										 pivotDatum, pivotIsNull, pivotFullDatum);
			if (dist > 0)
				break;
			if (dist == 0)
			{
				mkqs_swap(bounds->lessEnd, bounds->lessStart, x);
				bounds->lessStart++;
			}
			bounds->lessEnd++;
		}

		/* Scan from the right, moving equal values to the right edge. */
		while (bounds->lessEnd <= bounds->greaterStart)
		{
			dist = MKQS_COMPARE_TO_PIVOT(x + bounds->greaterStart, depth,
										 state, sortKey,
										 pivotDatum, pivotIsNull, pivotFullDatum);
			if (dist < 0)
				break;
			if (dist == 0)
			{
				mkqs_swap(bounds->greaterStart, bounds->greaterEnd, x);
				bounds->greaterEnd--;
			}
			bounds->greaterStart--;
		}

		if (bounds->lessEnd > bounds->greaterStart)
			return pivotIsNull;
		mkqs_swap(bounds->lessEnd, bounds->greaterStart, x);
		bounds->lessEnd++;
		bounds->greaterStart--;
	}
}

#undef MKQS_COMPARE_TO_PIVOT
#undef MKQS_APPLY_COMPARE
#undef MKQS_COMPARE_TUPLE
#undef MKQS_COMPARE_DATUM
#undef MKQS_GET_DATUM
#undef MKQS_PARTITION
#undef MKQS_USE_ABBREVIATION
#undef MKQS_BASE_NAME
#undef MKQS_MAKE_NAME
#undef MKQS_MAKE_NAME_
#undef MKQS_MAKE_PREFIX
